mex('-output','ipopt',...
    '-R2018a',...
    '-I/build/include/coin-or',...
    '-I/build/include',...
    '-I/build/include/coin-or/mumps',...
    '"/build/lib/libipopt.a"',...
    '"/build/lib/libcoinhsl.a"',...
    '"/build/lib/libcoinmumps.a"',...
    '"/usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblas.a"',...
    '-lm',...
    '-lpthread',... 
    '-lgfortran',...
    'main.cpp')

