name: Ipopt-Mex

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
#   schedule:
#     - cron: "23 13 3 * *"

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
    - name: Docker Image Update Checker
      id: baseupdatecheck
      uses: lucacome/docker-image-update-checker@v1.1.0
      with:
        base-image: mathworks/matlab:latest
        image: ${{ secrets.DOCKER_USER }}/ipoptmexstatic 
      if: steps.baseupdatecheck.outputs.needs-updating == 'true'
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_USER }}/ipoptmex:latest
          ${{ secrets.DOCKER_USER }}/ipoptmex:${{ github.sha }}


