name: Ipopt-Mex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # builder:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Set up QEMU
  #     uses: docker/setup-qemu-action@v2
  #   - name: Set up Docker Buildx
  #     uses: docker/setup-buildx-action@v2
  #   - name: Docker login
  #     uses: docker/login-action@v2
  #     with:
  #       username: ${{ secrets.DOCKER_USER }}
  #       password: ${{ secrets.DOCKER_HUB }}
  #   - name: Build and push
  #     uses: docker/build-push-action@v3
  #     with:
  #       push: true
  #       tags: |
  #           ${{ secrets.DOCKER_USER }}/ipoptmex:latest
  #           ${{ secrets.DOCKER_USER }}/ipoptmex:${{ github.sha }}
  #       secrets: |
  #           "matlab_license=${{ secrets.MATLAB_LICENSE }}"
  compiler:
    runs-on: ubuntu-latest
    # needs: builder
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB }}
    - name: Pull image
      run: | 
        docker pull ${{ secrets.DOCKER_USER }}/ipoptmex:latest
        docker run --rm -v $(pwd):/repo --mac-address=${{ secrets.MATLAB_MAC }} --shm-size=512M --mount=type=secret,id=matlab_license -e MLM_LICENSE_FILE=/run/secrets/matlab_license ${{ secrets.DOCKER_USER }}/ipoptmex:latest -batch "cd /repo; make"
        ls -lAR

