name: Ipopt-Mex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: false
        tags: |
            ipoptmex:latest
        secrets: |
            "matlab_license=${{ secrets.MATLAB_LICENSE }}"
    - name: Build mex
      run: |
        docker run --rm --mac-address=${{ secrets.MATLAB_MAC }} --shm-size=512M -v $GITHUB_WORKSPACE:/repo -t ipoptmex:latest -batch "cd /repo;make"
          
