name: Static-Mex

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
          ${{ secrets.DOCKER_USER }}/ipoptmexstatic:latest
          ${{ secrets.DOCKER_USER }}/ipoptmexstatic:${{ github.sha }}
        file: $GITHUB_WORKSPACE/.devcontainer/Dockerfile
        context: $GITHUB_WORKSPACE


