name: Test-Run

on:
  workflow_run:
    workflows: ["Static-Mex"]
    types:
      - completed
  workflow_dispatch:

jobs:
  tester:
    runs-on: ubuntu-latest
    # outputs:
    #   testresult: ${{ steps.testrun.outputs.testresult }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3.4.0
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB }}
    - name: Run Test
      id: testrun
      run: |
        docker pull ${{ secrets.DOCKER_USER }}/ipoptmexstatic:latest
        docker run --rm --mac-address=${{ secrets.MATLAB_MAC }} --shm-size=512m --network=bridge -v $(pwd)/test:/workspace  -t ${{ secrets.DOCKER_USER }}/ipoptmexstatic:latest ${{ secrets.THE_SECRET }} "cd('/workspace');run('tester.m')"
