name: Test-Run

on:
  workflow_run:
    workflows: ["Static-Mex"]
    types:
      - completed

jobs:
  tester:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_HUB }}
    - name: Run Test
      run: |
        docker pull ${{ secrets.DOCKER_USER }}/ipoptmexstatic:latest
        docker run --rm --mac-address=${{ secrets.MATLAB_MAC }} --shm-size=512m --network=bridge -e MLM_LICENSE_FILE=/home/matlab/license.lic -v ${{ github.workspace }}:/workspace --entrypoint=/workspace/testrunner.sh -e THE_SECRET=$THE_SECRET -t ${{ secrets.DOCKER_USER }}/ipoptmexstatic:latest